package org.embeddedt.modernfix.forge.capability;

import net.minecraft.core.Direction;
import net.minecraftforge.common.capabilities.Capability;
import net.minecraftforge.common.util.LazyOptional;
import org.jetbrains.annotations.Nullable;

/**
 * Superclass of the hidden classes generated by {@link CapabilityProviderDispatcherGenerator}.
 */
public abstract class GeneratedDispatcher {
    public abstract <T> LazyOptional<T> getCapability(Capability<T> cap, @Nullable Direction side);
}
